version: "3.7"

services:

  web:
    image: nginx:1.17
    ports:
      - 81:81
    volumes:
      - /Users/zychm/Docker-101/build:/var/www/public_html
      - /Users/zychm/Docker-101/docker/nginx.conf:/etc/nginx/conf.d/nginx.conf